### ISSUE TITLE
mikado-compile error when html text has newlines

### ISSUE THREAD

**Issue by hsnoil** [nextapps-de/mikado#77]
If you run this through `npx mikado-compile template/app.html`

```html
<main>
  <header>
    <nav></nav>
  </header>
  <section>
    <p>
test
</p>
  </section>
  <footer>
    <nav></nav>
  </footer>
</main>
```

you get the following error:
```
Compile templates with 'default' strategy ...
(node:20996) UnhandledPromiseRejectionWarning: SyntaxError: Invalid or unexpected token
    at Function (<anonymous>)
    at module.exports (/home/noil/Documents/javascript/mikado/node_modules/mikado/compiler/compile.js:234:27)
    at compiler (/home/noil/Documents/javascript/mikado/node_modules/mikado/compiler/cli.js:138:12)
    at /home/noil/Documents/javascript/mikado/node_modules/mikado/compiler/cli.js:298:17
(node:20996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If you have no newlines like this, it compiles fine:
```
<main>
  <header>
    <nav></nav>
  </header>
  <section>
    <p>test</p>
  </section>
  <footer>
    <nav></nav>
  </footer>
</main>
```

**Comment by ts-thomas** [comment]
Thanks for the report. It is now fixed. Also, I added a test for whitespaces: https://github.com/nextapps-de/mikado/blob/master/test/tpl/whitespace.html
Let me know if you find anything else. Thanks a lot.

**Comment by hsnoil** [comment]
Seems to be working now, thanks!
