### ISSUE TITLE
compiler error: replaceAll is not a function

### ISSUE THREAD

**Issue by hsnoil** [nextapps-de/mikado#79]
I loaded up latest todomvc, did npm update. then ran:

```
npx mikado-compile template/ --compact --force --module
```
I got the following error:
```
Compile templates with 'compact' strategy ...
(node:35291) UnhandledPromiseRejectionWarning: TypeError: (inc[i].join(...) + ";").replaceAll is not a function
    at module.exports (/home/noil/Documents/javascript/Untitled Folder/mikado-master/examples/todomvc/node_modules/mikado/compiler/compile.js:327:50)
    at compiler (/home/noil/Documents/javascript/Untitled Folder/mikado-master/examples/todomvc/node_modules/mikado/compiler/cli.js:138:12)
    at /home/noil/Documents/javascript/Untitled Folder/mikado-master/examples/todomvc/node_modules/mikado/compiler/cli.js:290:21
    at loopFiles (/home/noil/Documents/javascript/Untitled Folder/mikado-master/examples/todomvc/node_modules/mikado/compiler/cli.js:192:72)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/noil/Documents/javascript/Untitled Folder/mikado-master/examples/todomvc/node_modules/mikado/compiler/cli.js:286:13
(node:35291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Edit: A more minimum example that gives the same error is:
```
<main>
  <section>
{{@ const value = "test"; }}
    <p>{{value}}</p>
  </section>
</main>
```

**Comment by ts-thomas** [comment]
Looks like you are running an older Node.js version. I removed the `replaceAll` in the latest version.

**Comment by hsnoil** [comment]
Okay, seems fixed, thanks!
