### ISSUE TITLE
Compiler destination folder issues

### ISSUE THREAD

**Issue by hsnoil** [nextapps-de/mikado#81]
When you try to run:
```
npx mikado-compile template/ -d compiled/ --compact --force --module
```
It just creates a file called "compiled" and treating both results as a file, not a folder:
```
Compile templates with 'compact' strategy ...
/home/noil/Documents/javascript/mikado/template/try.html > /home/noil/Documents/javascript/mikado/compiled
/home/noil/Documents/javascript/mikado/template/app.html > /home/noil/Documents/javascript/mikado/compiled
Done.
```
On top of that, if you try to do a single file and output it to a folder that doesn't exist:
```
npx mikado-compile template/subfolder/try.html -d compiled/subfolder/try.html --compact --force --module
```
You also get an error
```
Compile templates with 'compact' strategy ...
(node:38681) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/noil/Documents/javascript/mikado/compiled/subfolder/try.html'
    at Object.openSync (fs.js:462:3)
    at writeFileSync (fs.js:1384:35)
    at module.exports (/home/noil/Documents/javascript/mikado/node_modules/mikado/compiler/compile.js:344:9)
    at compiler (/home/noil/Documents/javascript/mikado/node_modules/mikado/compiler/cli.js:138:12)
    at /home/noil/Documents/javascript/mikado/node_modules/mikado/compiler/cli.js:298:17
(node:38681) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38681) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ts-thomas** [comment]
I've added support for mixed inputs as `src` and `dest`. Please try this again on the latest version.

**Comment by hsnoil** [comment]
The folder issue is fixed, thanks!

The nested file issue isn't fixed though, it still gives an error:

```
$ npx mikado-compile template/subfolder/try.html -d compiled/subfolder/try.html --compact --force --module
Compile templates with 'compact' strategy ...
(node:41774) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/noil/Documents/javascript/mikado/compiled/subfolder/try.html'
    at Object.openSync (fs.js:462:3)
    at writeFileSync (fs.js:1384:35)
    at module.exports (/home/noil/Documents/javascript/mikado/node_modules/mikado/compiler/compile.js:354:9)
    at compiler (/home/noil/Documents/javascript/mikado/node_modules/mikado/compiler/cli.js:159:12)
    at /home/noil/Documents/javascript/mikado/node_modules/mikado/compiler/cli.js:319:17
(node:41774) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:41774) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ts-thomas** [comment]
The command should be:
`npx mikado-compile template/subfolder/try.html -d compiled/subfolder/try.js --compact --force --module`
it needs `js` for destination files. I've added a patch for this which appends ".js" in this situation. I will update later.

**Comment by hsnoil** [comment]
Oops, sorry. But even when I run that it still gives the error. Only workaround is just using a directory:
`npx mikado-compile template/subfolder/try.html -d compiled/subfolder/ --compact --force --module`

**Comment by ts-thomas** [comment]
This should have been fixed now.

**Comment by hsnoil** [comment]
@ts-thomas 

It seems destination doesn't has a minor issue, when I do:
```
npx mikado-compile -d ./compiled/ -s ./template/ --compact --force --module
```
The destination compiles look like `compiled/name` and not `name`. My guess since it is going off the src as mentioned when it should go off dest if it is available

**Comment by ts-thomas** [comment]
@hsnoil good eyes ;) I will fix this
